apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-container
          image: {{ .Values.components.backend.image }}
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: SECRET_KEY
            - name: DEBUG
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: DEBUG
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: dsn
            - name: ALLOWED_HOSTS
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: ALLOWED_HOSTS
            - name: SSL_CRT
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: SSL_CRT
            - name: name
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: name
            - name: port
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: port
            - name: root.crt
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: root.crt
            - name: dsn
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: dsn
            - name: host
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: host
            - name: username
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: username
            - name: password
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
          ports:
            - containerPort: 80
