version: "3"

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  web:
    build:
      context: backend_main_django
      args:
        GIT_COMMIT: ${GIT_COMMIT:-unknown}
    image: aleksandr301/django_app:${DOCKER_TAG:-latest}
    volumes:
      - ./backend_main_django:/code
    environment: 
      SECRET_KEY: ${WEB_SECRET_KEY}
      DEBUG: ${WEB_DEBUG}
      DATABASE_URL: ${WEB_DATABASE_URL}
      ALLOWED_HOSTS: ${WEB_ALLOWED_HOSTS}
    ports:
      - 127.0.0.1:8080:80
    depends_on:
      - db

volumes:
  db_data:
