container:
  django:
    image: aleksandr301/django_app:latest
  postgres:
    image: postgres:12.0-alpine
deployment:
  replicasDjango: 1
  replicasPostgres: 1
global:
  ingress:
    host: edu-aleksandr-ushakov.yc-sirius-dev.pelid.team
    port: 80
  service:
    postgresPort: 5432
    djangoPort: 80
job:
  timerTask: "0 3 * * *"
  clearsession:
    startingDeadlineSeconds: 360
    ttlSecondsAfterFinished: 3600
  migration:
    ttlSecondsAfterFinished: 600